[package]
name = "szm-massage-kosmetik"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
dotenv = "0.15.0"
env_logger = "0.11.5"
hashbrown = "0.15.0"
lazy_static = "1.5.0"
serde = "1.0.210"
tera = "1.20.0"
