<!-- TODO: make these curves mobile friendly -->
<div class="curves">
  <div class="curve-1">
    <svg id="curve-1" width="100%" height="100%" viewBox="0 0 1920 1080" preserveAspectRatio="none">
      <path d="M 0 0 H 250 V 500 C 250 884 1920 750 1920 1080 H 0 Z"></path>
    </svg>
  </div>

  <div class="curve-2">
    <svg id="curve-2" width="100%" height="100%" viewBox="0 0 1920 1080" preserveAspectRatio="none">
      <path d="M 0 0 H 250 V 450 C 250 884 1920 625 1920 1080 H 0 Z"></path>
    </svg>
  </div>

  <div class="curve-3">
    <svg id="curve-3" width="100%" height="100%" viewBox="0 0 1920 1080" preserveAspectRatio="none">
      <path d="M 0 0 H 250 V 400 C 250 884 1920 500 1920 1080 H 0 Z"></path>
    </svg>
  </div>
</div>

<div class="three-color-section">
  <div class="showcase">

    <div id="trager-card" class="card">
      <div class="card-front">
        <h1>Trager</h1>
        <hr>
        <button id="trager-button">Mehr erfahren</button>
      </div>

      <div class="card-back">
        <ul>
          <li><a href="/trager#trager">Trager&reg;</a></li>
          <li><a href="/trager#mentastic">Mentastic</a></li>
        </ul>
      </div>
    </div>

    <div id="massage-card" class="card">
      <div class="card-front">
        <h1>Massage</h1>
        <hr>
        <button id="massage-button">Mehr erfahren</button>
      </div>

      <div class="card-back">
        <ul>
          <li><a href="/massage#klassische-massage">Klassische Massage</a></li>
          <li><a href="/massage#ruecken-nackenmassage">Rücken- und Nachenmassage</a></li>
          <li><a href="/massage#schroepfen">Schröpfen</a></li>
          <li><a href="/massage#schmerz">Schmerztherapie nach Liebscher & Bracht</a></li>
          <li><a href="/massage#fussreflexzonenmassage">Fussreflex&shy;zonenmassage</a></li>
        </ul>
      </div>
    </div>

    <div id="kosmetik-card" class="card">
      <div class="card-front">
        <h1>Kosmetik</h1>
        <hr>
        <button id="kosmetik-button">Mehr erfahren</button>
      </div>

      <div class="card-back">
        <ul>
          <li><a href="/kosmetik#fusspflege">Fusspflege</a></li>
          <li><a href="/kosmetik#medizinische-kosmetik">Medizinische Kosmetik</a></li>
          <li><a href="/kosmetik#aknebehandlung">Aknebehandlung</a></li>
          <li><a href="/kosmetik#antiaging">AntiAging</a></li>
          <li><a href="/kosmetik#mikrodermabrasion">Mikro&shy;dermabrasion</a></li>
          <li><a href="/kosmetik#microneedling">Microneedling</a></li>
          <li><a href="/kosmetik#klassische-kosmetik">Klassische Kosmetik</a></li>
          <li><a href="/kosmetik#manicure">Manicure</a></li>
          <li><a href="/kosmeitk#phyto-cell-behandlugn">Phyto-Cell Behandlung</a></li>
        </ul>
      </div>
    </div>

    <script>
      // This little script is responsible for turning the cards
      const trager_card = document.querySelector("#trager-card")
      const massage_card = document.querySelector("#massage-card")
      const kosmetik_card = document.querySelector("#kosmetik-card")

      // If the user clicks outside of the 3 cards all of them get turned back to normal
      document.querySelector("#home").addEventListener("pointerdown", (event) => {
        event.preventDefault()
        event.stopPropagation()

        if (!trager_card.contains(event.target)) {
          trager_card.classList.remove("turned")
        }

        if (!massage_card.contains(event.target)) {
          massage_card.classList.remove("turned")
        }

        if (!kosmetik_card.contains(event.target)) {
          kosmetik_card.classList.remove("turned")
        }
      })

      // Clicking the button on the Trager card turns it over and turns all other cards back to normal
      document.querySelector("#trager-button").addEventListener("pointerdown", (event) => {
        event.preventDefault()
        event.stopPropagation()

        trager_card.classList.add("turned")

        if (massage_card.classList.contains("turned")) {
          massage_card.classList.remove("turned")
        }

        if (kosmetik_card.classList.contains("turned")) {
          kosmetik_card.classList.remove("turned")
        }
      })

      // Clicking the button on the Massage card turns it over and turns all other cards back to normal
      document.querySelector("#massage-button").addEventListener("pointerdown", (event) => {
        event.preventDefault()
        event.stopPropagation()

        massage_card.classList.add("turned")

        if (trager_card.classList.contains("turned")) {
          trager_card.classList.remove("turned")
        }

        if (kosmetik_card.classList.contains("turned")) {
          kosmetik_card.classList.remove("turned")
        }
      })

      // Clicking the button on the Kosmetik card turns it over and turns all other cards back to normal
      document.querySelector("#kosmetik-button").addEventListener("pointerdown", (event) => {
        event.preventDefault()
        event.stopPropagation()

        kosmetik_card.classList.add("turned")

        if (trager_card.classList.contains("turned")) {
          trager_card.classList.remove("turned")
        }

        if (massage_card.classList.contains("turned")) {
          massage_card.classList.remove("turned")
        }
      })
    </script>

  </div>
</div>

<div class="transition">
  <img src="/img/layered-waves.svg" alt="Transition image">
</div>

<div class="location">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2702.1298177684384!2d8.529919515865654!3d47.37038471225848!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47900a03061a255b%3A0xb5dc345fde76c562!2sSelnaustrasse%2015%2C%208001%20Z%C3%BCrich!5e0!3m2!1sde!2sch!4v1617869147579!5m2!1sde!2sch" frameborder="0"></iframe>
</div>
