<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php // The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags ?>

    <?php // Base URL ?>
    <!--<base href="http://szm-massage-kosmetik.test">-->

    <?php // Document Title ?>
    <?= $this->tag->renderTitle() ?>

    <?php // Favicon ?>
    <link rel="shortcut icon" type="image/x-icon" href="<?= $this->url->get('img/rainbow-heart.ico') ?>"/>

    <?php // CSS ?>
    <!--<link rel="stylesheet" href="<?= $this->url->get('css/global-styles.css') ?>">-->
    <!--<link rel="stylesheet" href="<?= $this->url->get('css/navigation.css') ?>">-->
    <!--<link rel="stylesheet" href="<?= $this->url->get('css/footer.css') ?>">-->
    <?php // $this->assets->outputCss() ?>
    <link rel="stylesheet" href="<?= $this->url->get('css/style.css'); ?>">
  </head>

  <?php // TODO: add logo ?>
  <body>
    <!--<div id="szm-logo">
      <div>S</div>
      <div>z</div>
      <div>M</div>
    </div>-->

    <?php $this->partial('partials/nav'); ?>

    <main id="<?= $this->view->page ?>">
      <?= $this->getContent() ?>
    </main>

    <footer>
      <address>
        <a href="/"><h2>SzM</h2></a>
        <div>Szilvia Marosi</div>
        <div>Selnaustrasse 15</div>
        <div>8001 Zürich</div>
        <a href="tel:0794257491">📞 +41(0)79 425 74 91</a>
        <a href="mailto:szmmassage@gmail.com">📧 szmmassage@gmail.com</a>
      </address>

      <div>
        <h2>Angebote</h2>
        <a href="/trager">Trager&reg;</a>
        <a href="/massage">Massage</a>
        <a href="/kosmetik">Kosmetik</a>
      </div>

      <div>
        <h2>Weiteres</h2>
        <a href="/gutschein">Gutscheine</a>
        <a href="/termin">Termin buchen</a>
        <a href="/kontakt">Kontakt</a>
      </div>

      <div>
        <h2>&nbsp;</h2>
        <a href="/uebermich">Über mich</a>
        <a href="/uebermich/bildergallerie">Bildergallerie</a>
      </div>
    </footer>
  </body>
</html>

<script>
  // This little script makes the nav appear/disappear
  const nav = document.querySelector("nav")

  // Opens the menu when clicking the menu icon
  document.querySelector("#menu-icon").addEventListener("pointerdown", event => {
    event.stopPropagation()

    nav.classList.add("open")
  })

  // Closes the menu when clicking the X
  document.querySelector("#close-nav").addEventListener("pointerdown", event => {
    event.stopPropagation()

    nav.classList.remove("open")
  })

  // Closes the menu when clicking outside the menu
  document.querySelector("body").addEventListener("pointerdown", event => {
    event.stopPropagation()

    if (!nav.contains(event.target)) {
      nav.classList.remove("open")
    }
  })

  // Closes the menu when clicking outside the menu
  document.querySelector("main").addEventListener("pointerdown", event => {
    event.stopPropagation()

    if (!nav.contains(event.target)) {
      nav.classList.remove("open")
    }
  })
</script>

<?php // JS ?>
<?= $this->assets->outputJs() ?>
