<?php

function printNavElement($url, $thisPage, $pageNumber, $image, $text)
{
  $currentPage = '';

  if ($thisPage == $pageNumber)
  {
    $currentPage = 'current-page';
  }

  echo "
  <li>
    <a href=\"$url\" class=\"$currentPage\">
      <img src=\"$image\" alt=\"\" height=\"28\" width=\"28\">
      $text
    </a>
  </li>
  ";
}
?>
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php // The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags ?>

    <?php // Base URL ?>
    <base href="http://szm-massage-kosmetik.test">

    <?php // Document Title ?>
    <?= $this->tag->renderTitle() ?>

    <?php // Favicon ?>
    <link rel="shortcut icon" type="image/x-icon" href="<?= $this->url->get('img/rainbow-heart.ico') ?>"/>

    <?php // CSS ?>
    <link rel="stylesheet" href="<?= $this->url->get('css/global-styles.css') ?>">
    <link rel="stylesheet" href="<?= $this->url->get('css/navigation.css') ?>">
    <link rel="stylesheet" href="<?= $this->url->get('css/footer.css') ?>">
    <link rel="stylesheet" href="<?= $this->url->get('css/nerd-fonts.css') ?>">
    <?= $this->assets->outputCss() ?>
  </head>
  <body>
    <nav>
      <ul>
        <?php printNavElement('/', $this->view->page, 0, $this->url->get('img/home.svg'), 'SzM') ?>
        <?php printNavElement('/trager', $this->view->page, 1, $this->url->get('img/trager.svg'), 'Trager&reg;') ?>
        <?php printNavElement('/massage', $this->view->page, 2, $this->url->get('img/massage.svg'), 'Massage') ?>
        <?php printNavElement('/kosmetik', $this->view->page, 3, $this->url->get('img/cosmetics.svg'), 'Kosmetik') ?>
        <?php printNavElement('/uebermich', $this->view->page, 4, $this->url->get('img/person.svg'), 'Über&nbsp;mich') ?>
        <?php printNavElement('/gutschein', $this->view->page, 5, $this->url->get('img/check.svg'), 'Gutschein') ?>
        <?php printNavElement('/termin', $this->view->page, 6, $this->url->get('img/calendar.svg'), 'Termin') ?>
        <?php printNavElement('/kontakt', $this->view->page, 7, $this->url->get('img/contact.svg'), 'Kontakt') ?>
      </ul>
    </nav>

    <main id="main">
      <?= $this->getContent() ?>
    </main>

    <footer>
      <div class="angebote">
        <h2>Angebote</h2>
        <a href="/trager">Trager&reg;</a>
        <a href="/massage">Massage</a>
        <a href="/kosmetik">Kosmetik</a>
      </div>

      <div>
        <h2>Weiteres</h2>
        <a href="/gutschein">Gutscheine</a>
        <a href="/termin">Termin buchen</a>
        <a href="/kontakt">Kontakt</a>
      </div>

      <div>
        <h2>&nbsp;</h2>
        <a href="/uebermich">Über mich</a>
      </div>
    </footer>

    <?php // JS ?>
    <?= $this->assets->outputJs() ?>
  </body>
</html>
