<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php // The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags ?>

    <?php // Base URL ?>
    <base href="http://szm-massage-kosmetik.test">

    <?php // Document Title ?>
    <?= $this->tag->renderTitle() ?>

    <?php // Favicon ?>
    <link rel="shortcut icon" type="image/x-icon" href="<?= $this->url->get('img/rainbow-heart.ico') ?>"/>

    <?php // CSS ?>
    <link rel="stylesheet" href="<?= $this->url->get('css/global-styles.css') ?>">
    <link rel="stylesheet" href="<?= $this->url->get('css/navigation.css') ?>">
    <link rel="stylesheet" href="<?= $this->url->get('css/footer.css') ?>">
    <?= $this->assets->outputCss() ?>
  </head>
  <body>
    <div id="szm-logo">
      <div>S</div>
      <div>z</div>
      <div>M</div>
    </div>

    <?php $this->partial('partials/nav'); ?>

    <main id="main">
      <?php // TODO: add logo ?>
      <?= $this->getContent() ?>
    </main>

    <footer id="footer">
      <address>
        <a href="/"><h2>SzM</h2></a>
        <div>Szilvia Marosi</div>
        <div>Selnaustrasse 15</div>
        <div>8001 Zürich</div>
        <a href="tel:0794257491">📞 +41(0)79 425 74 91</a>
        <a href="mailto:szmmassage@gmail.com">📧 szmmassage@gmail.com</a>
      </address>

      <div>
        <h2>Angebote</h2>
        <a href="/trager">Trager&reg;</a>
        <a href="/massage">Massage</a>
        <a href="/kosmetik">Kosmetik</a>
      </div>

      <div>
        <h2>Weiteres</h2>
        <a href="/gutschein">Gutscheine</a>
        <a href="/termin">Termin buchen</a>
        <a href="/kontakt">Kontakt</a>
      </div>

      <div>
        <h2>&nbsp;</h2>
        <a href="/uebermich">Über mich</a>
        <a href="/uebermich/bildergallerie">Bildergallerie</a>
      </div>
    </footer>

    <?php // JS ?>
    <?= $this->assets->outputJs() ?>
  </body>
</html>
